// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASKuBLSEIOlalw6QcDZY0oj_H5LXdh1yo',
    appId: '1:542174991248:web:922d3dcde0dade90639915',
    messagingSenderId: '542174991248',
    projectId: 'dimensy-19190',
    authDomain: 'dimensy-19190.firebaseapp.com',
    storageBucket: 'dimensy-19190.appspot.com',
    measurementId: 'G-S3RXBL0GNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCZfHRu-6Hr-E3sJrGZQJDTz4LvqcCHOA',
    appId: '1:542174991248:android:8f83f50b47fa837e639915',
    messagingSenderId: '542174991248',
    projectId: 'dimensy-19190',
    storageBucket: 'dimensy-19190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5DP-Xs4uNPxJMLCrime6ueuUmE8AzN38',
    appId: '1:542174991248:ios:5bf9168dcbf3a51c639915',
    messagingSenderId: '542174991248',
    projectId: 'dimensy-19190',
    storageBucket: 'dimensy-19190.appspot.com',
    iosClientId: '542174991248-fh9jqaomuos8pdr6c1c7td6r2np2uqgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.militarymessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5DP-Xs4uNPxJMLCrime6ueuUmE8AzN38',
    appId: '1:542174991248:ios:5bf9168dcbf3a51c639915',
    messagingSenderId: '542174991248',
    projectId: 'dimensy-19190',
    storageBucket: 'dimensy-19190.appspot.com',
    iosClientId: '542174991248-fh9jqaomuos8pdr6c1c7td6r2np2uqgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.militarymessenger',
  );
}
